lane :bonjour do
  scan(
  code_coverage: true
  )
  xcov
end

lane :deploy do
  if git_branch() == "master"
    version = get_version_number()
    set_github_release(
      repository_name: "faslane-demo",
      name: version,
      tag_name: "v_#{version}",
      description: changelog_from_git_commits(),
      commitish: "master"
    )
  end
end
